env:
    global:
        - PYTHONHASHSEED=random
language: python
dist: xenial
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.6
        - os: osx
          language: generic
install:
    pip install chardet flake8
script:
    - python setup.py test
    - flake8 src
