# run these tests from the src directory
python -m unittest  cssutils.tests2.test_codec
python -m unittest  cssutils.tests2.test_csscharsetrule
python -m unittest  cssutils.tests2.test_csscomment
python -m unittest  cssutils.tests2.test_cssfontfacerule
python -m unittest  cssutils.tests2.test_cssimportrule
python -m unittest  cssutils.tests2.test_cssmediarule
python -m unittest  cssutils.tests2.test_cssnamespacerule
python -m unittest  cssutils.tests2.test_csspagerule
python -m unittest  cssutils.tests2.test_cssproperties
python -m unittest  cssutils.tests2.test_cssrule
python -m unittest  cssutils.tests2.test_cssrulelist
python -m unittest  cssutils.tests2.test_cssstyledeclaration
python -m unittest  cssutils.tests2.test_cssstylerule
python -m unittest  cssutils.tests2.test_cssstylesheet
python -m unittest  cssutils.tests2.test_cssunknownrule
python -m unittest  cssutils.tests2.test_cssutils
python -m unittest  cssutils.tests2.test_cssutilsimport
python -m unittest  cssutils.tests2.test_cssvalue
python -m unittest  cssutils.tests2.test_cssvariablesdeclaration
python -m unittest  cssutils.tests2.test_cssvariablesrule
python -m unittest  cssutils.tests2.test_domimplementation
python -m unittest  cssutils.tests2.test_errorhandler
python -m unittest  cssutils.tests2.test_helper
python -m unittest  cssutils.tests2.test_marginrule
python -m unittest  cssutils.tests2.test_medialist
python -m unittest  cssutils.tests2.test_mediaquery
python -m unittest  cssutils.tests2.test_parse
python -m unittest  cssutils.tests2.test_prodparser
python -m unittest  cssutils.tests2.test_profiles
python -m unittest  cssutils.tests2.test_properties
python -m unittest  cssutils.tests2.test_property
python -m unittest  cssutils.tests2.test_scripts_csscombine
python -m unittest  cssutils.tests2.test_selector
python -m unittest  cssutils.tests2.test_selectorlist
python -m unittest  cssutils.tests2.test_serialize
python -m unittest  cssutils.tests2.test_settings
python -m unittest  cssutils.tests2.test_stylesheet
python -m unittest  cssutils.tests2.test_tokenize2
python -m unittest  cssutils.tests2.test_util
python -m unittest  cssutils.tests2.test_value
python -m unittest  cssutils.tests2.test_x
python -m unittest  cssutils.tests2.test_encutils
