# run this script from the src/ directory
python3 -m unittest  cssutils.tests.test_codec
python3 -m unittest  cssutils.tests.test_csscharsetrule
python3 -m unittest  cssutils.tests.test_csscomment
python3 -m unittest  cssutils.tests.test_cssfontfacerule
python3 -m unittest  cssutils.tests.test_cssimportrule
python3 -m unittest  cssutils.tests.test_cssmediarule
python3 -m unittest  cssutils.tests.test_cssnamespacerule
python3 -m unittest  cssutils.tests.test_csspagerule
python3 -m unittest  cssutils.tests.test_cssproperties
python3 -m unittest  cssutils.tests.test_cssrule
python3 -m unittest  cssutils.tests.test_cssrulelist
python3 -m unittest  cssutils.tests.test_cssstyledeclaration
python3 -m unittest  cssutils.tests.test_cssstylerule
python3 -m unittest  cssutils.tests.test_cssstylesheet
python3 -m unittest  cssutils.tests.test_cssunknownrule
python3 -m unittest  cssutils.tests.test_cssutils
python3 -m unittest  cssutils.tests.test_cssutilsimport
python3 -m unittest  cssutils.tests.test_cssvalue
python3 -m unittest  cssutils.tests.test_cssvariablesdeclaration
python3 -m unittest  cssutils.tests.test_cssvariablesrule
python3 -m unittest  cssutils.tests.test_domimplementation
python3 -m unittest  cssutils.tests.test_errorhandler
python3 -m unittest  cssutils.tests.test_helper
python3 -m unittest  cssutils.tests.test_marginrule
python3 -m unittest  cssutils.tests.test_medialist
python3 -m unittest  cssutils.tests.test_mediaquery
python3 -m unittest  cssutils.tests.test_parse
python3 -m unittest  cssutils.tests.test_prodparser
python3 -m unittest  cssutils.tests.test_profiles
python3 -m unittest  cssutils.tests.test_properties
python3 -m unittest  cssutils.tests.test_property
python3 -m unittest  cssutils.tests.test_scripts_csscombine
python3 -m unittest  cssutils.tests.test_selector
python3 -m unittest  cssutils.tests.test_selectorlist
python3 -m unittest  cssutils.tests.test_serialize
python3 -m unittest  cssutils.tests.test_settings
python3 -m unittest  cssutils.tests.test_stylesheet
python3 -m unittest  cssutils.tests.test_tokenize2
python3 -m unittest  cssutils.tests.test_util
python3 -m unittest  cssutils.tests.test_value
python3 -m unittest  cssutils.tests.test_x
python3 -m unittest cssutils.tests.test_encutils
